/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import javax.swing.JLabel;
import javax.swing.JTextField;
import quanlydatban.Dao.TableDao;

/**
 *
 * @author HELLO
 */
public class cardTable extends javax.swing.JPanel {
    
    /**
     * Creates new form cardTable
     */
    private TableUpdateListener updateListener;
    private String tableId;
    
    TableDao tbDao = new TableDao();
    
    public void setUpdateListener(TableUpdateListener listener) {
        this.updateListener = listener;
    }
    public void setTableId(String id) {
        this.tableId = id;
    }
    
    public cardTable() {
        initComponents();
    }

    public void setTxtIdTable(String txtIdTable) {
        this.txtIdTable.setText(this.txtIdTable.getText()+txtIdTable);
    }

    public void setTxtSeats(String seat){
        this.txtSeats.setText(this.txtSeats.getText()+seat);
    }

    public void setTxtTrangThai(String txtTrangThai) {
        this.txtTrangThai.setText(txtTrangThai);
    }
    
    private void handleUpdate(String status) {
        if (this.tableId == null || this.tableId.isEmpty()) {
            System.out.println("Lỗi: Không có ID bàn.");
            return;
        }
        // 1. Cập nhật DB
        tbDao.updateStatus(tableId, status); 
    
        // 2. Cập nhật giao diện của Card hiện tại (Để người dùng thấy thay đổi ngay lập tức)
        this.txtTrangThai.setText(status);
    
        // 3. **GỌI CALLBACK** (Thông báo cho pnScreenQuanLyBanAn)
        if (updateListener != null) {
            updateListener.onTableStatusUpdated();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtIdTable = new javax.swing.JLabel();
        txtSeats = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        displayTrangthai = new javax.swing.JLabel();
        modeEmpty = new javax.swing.JButton();
        modeBooked = new javax.swing.JButton();
        modeUsing = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setMaximumSize(new java.awt.Dimension(200, 280));
        setMinimumSize(new java.awt.Dimension(200, 280));
        setPreferredSize(new java.awt.Dimension(200, 280));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        txtIdTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdTable.setForeground(new java.awt.Color(51, 102, 255));
        txtIdTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIdTable.setText("Bàn : ");
        txtIdTable.setMaximumSize(new java.awt.Dimension(3000, 30));
        jPanel1.add(txtIdTable);

        txtSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSeats.setText("Số chỗ : ");
        txtSeats.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel1.add(txtSeats);

        txtTrangThai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTrangThai.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel1.add(txtTrangThai);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 10));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        displayTrangthai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        displayTrangthai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayTrangthai.setText("Thay đổi trạng thái : ");
        displayTrangthai.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 0));
        jPanel2.add(displayTrangthai, new java.awt.GridBagConstraints());

        modeEmpty.setBackground(new java.awt.Color(255, 255, 153));
        modeEmpty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modeEmpty.setText("Trống");
        modeEmpty.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 10));
        modeEmpty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeEmptyMouseClicked(evt);
            }
        });
        modeEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeEmptyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanel2.add(modeEmpty, gridBagConstraints);

        modeBooked.setBackground(new java.awt.Color(255, 102, 102));
        modeBooked.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modeBooked.setText("Đã đặt");
        modeBooked.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 10));
        modeBooked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeBookedMouseClicked(evt);
            }
        });
        modeBooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeBookedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanel2.add(modeBooked, gridBagConstraints);

        modeUsing.setBackground(new java.awt.Color(102, 255, 102));
        modeUsing.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modeUsing.setText("Đang dùng");
        modeUsing.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 10));
        modeUsing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeUsingMouseClicked(evt);
            }
        });
        modeUsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeUsingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 10);
        jPanel2.add(modeUsing, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void modeUsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeUsingActionPerformed
        // TODO add your handling code here:
        handleUpdate("Using");
    }//GEN-LAST:event_modeUsingActionPerformed

    private void modeBookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeBookedActionPerformed
        // TODO add your handling code here:
        handleUpdate("Booked");
    }//GEN-LAST:event_modeBookedActionPerformed

    private void modeEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeEmptyActionPerformed
        // TODO add your handling code here:
        handleUpdate("Empty");
        
    }//GEN-LAST:event_modeEmptyActionPerformed

    private void modeEmptyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeEmptyMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_modeEmptyMouseClicked

    private void modeBookedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeBookedMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_modeBookedMouseClicked

    private void modeUsingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeUsingMouseClicked
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_modeUsingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayTrangthai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modeBooked;
    private javax.swing.JButton modeEmpty;
    private javax.swing.JButton modeUsing;
    private javax.swing.JLabel txtIdTable;
    private javax.swing.JLabel txtSeats;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables


}
