/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlydatban.View.HomePage;


import quanlydatban.Model.Table;
import java.sql.Connection;
import quanlydatban.Dao.ConnectionDatabase;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Panel;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.sql.Statement;
import java.sql.ResultSet;



import java.util.List;
import quanlydatban.Dao.AccountDao;
import quanlydatban.Dao.TableDao;
import quanlydatban.Model.Account;

import quanlydatban.View.dangnhap.JFLoginUI;

/**
 *
 * @author HELLO
 */
public class Main_menu extends javax.swing.JFrame {
    // Khai báo ở đầu lớp Main_menu, cùng nơi bạn khai báo các JButton
    private javax.swing.JButton activeButton;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main_menu.class.getName());
    TableDao table = new TableDao();
    AccountDao acc = new AccountDao();
    
    List<Account> AccList = acc.getAllAcount();
    List<Table> tbList = table.getAllTable();
    JFLoginUI loginUI =new JFLoginUI();
    public Account AccCurrent;
    /**
     * Creates new form Main_menu
     */
    
    public Main_menu(Account cur) throws SQLException {
        
        AccCurrent = cur;
        initComponents();
//        if (this.AccCurrent != null) { 
//            this.txtWelcome.setText(""+"Chào Mừng " + cur.getUsername()); 
//        }
        
//        this.txtWelcome.setText(this.txtWelcome.getString()+ "something");
        // 1. Khởi tạo đối tượng từ File Panel
        pnScreenQuanLyBanAn banAnPanel = new pnScreenQuanLyBanAn();
        pnScreenDatBanMoi datBanPanel = new pnScreenDatBanMoi(this);
        pnScreenDanhSach danhSachPanel =new pnScreenDanhSach();
        
        banAnPanel.setDatBanMoiListener(datBanPanel);
        datBanPanel.setQuanLyBanListener(banAnPanel);
        datBanPanel.setDanhSachListener(danhSachPanel);
        
        
        pnScreenDanhSachEmployee danhsachEm = new pnScreenDanhSachEmployee(); 
        
        
        
        // 2. Thêm vào pnMain với một tên chuỗi CỐ ĐỊNH và DUY NHẤT
        // Cấu trúc: pnMain.add(đối tượng_Panel, "Tên_Card");
        pnMain.add(banAnPanel, "pnScreenQuanLyBanAn");
        pnMain.add(datBanPanel, "pnScreenDatBanMoi");
        pnMain.add(danhSachPanel, "pnScreenDanhSach");
        pnMain.add(danhsachEm , "pnScreenDanhSachEmployee");       
//          ^ Đối tượng Panel      ^ Tên Card
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenQuanLyBan1 = new javax.swing.JPanel();
        titleQLB1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        main1 = new javax.swing.JPanel();
        thongkebanan1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtCountEmpty1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtCountBooked1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtCountUsing1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sodobanan1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableListPanel1 = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new RoundedButton();
        jButton2 = new RoundedButton();
        jButton3 = new RoundedButton();
        jButton4 = new RoundedButton();
        btnLogOut = new RoundedButton();
        pnMain = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        screenQuanLyBan1.setLayout(new java.awt.BorderLayout());

        titleQLB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titleQLB1.setPreferredSize(new java.awt.Dimension(870, 70));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Quan Ly Ban An");

        javax.swing.GroupLayout titleQLB1Layout = new javax.swing.GroupLayout(titleQLB1);
        titleQLB1.setLayout(titleQLB1Layout);
        titleQLB1Layout.setHorizontalGroup(
            titleQLB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleQLB1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addContainerGap(899, Short.MAX_VALUE))
        );
        titleQLB1Layout.setVerticalGroup(
            titleQLB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleQLB1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(20, 20, 20))
        );

        screenQuanLyBan1.add(titleQLB1, java.awt.BorderLayout.PAGE_START);

        main1.setLayout(new java.awt.BorderLayout());

        thongkebanan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Ban Trong");

        txtCountEmpty1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountEmpty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountEmpty1.setBorder(null);
        txtCountEmpty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountEmpty1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(txtCountEmpty1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountEmpty1)
                .addGap(12, 12, 12))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(233, 80));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Da Dat");

        txtCountBooked1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountBooked1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountBooked1.setBorder(null);
        txtCountBooked1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountBooked1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtCountBooked1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountBooked1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Dang Dung");

        txtCountUsing1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountUsing1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountUsing1.setBorder(null);
        txtCountUsing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountUsing1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCountUsing1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountUsing1)
                .addGap(14, 14, 14))
        );

        jLabel21.setText("Thong ke ban an");

        javax.swing.GroupLayout thongkebanan1Layout = new javax.swing.GroupLayout(thongkebanan1);
        thongkebanan1.setLayout(thongkebanan1Layout);
        thongkebanan1Layout.setHorizontalGroup(
            thongkebanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkebanan1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(thongkebanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongkebanan1Layout.setVerticalGroup(
            thongkebanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongkebanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thongkebanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        main1.add(thongkebanan1, java.awt.BorderLayout.PAGE_START);

        sodobanan1.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setViewportView(tableListPanel1);

        sodobanan1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        main1.add(sodobanan1, java.awt.BorderLayout.CENTER);

        screenQuanLyBan1.add(main1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Managerment System");
        setMinimumSize(new java.awt.Dimension(1070, 600));

        pnMenu.setBackground(new java.awt.Color(26, 41, 59));
        pnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMenu.setPreferredSize(new java.awt.Dimension(200, 1100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý đặt bàn ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 200));

        jButton1.setBackground(new java.awt.Color(26, 41, 59));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quản lý bàn");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(26, 41, 59));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Đặt bàn mới");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(26, 41, 59));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xem danh sách bàn");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(26, 41, 59));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Danh sách nhân viên");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(26, 41, 59));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setBorder(null);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 735, Short.MAX_VALUE))
        );

        getContentPane().add(pnMenu, java.awt.BorderLayout.LINE_START);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );

        pnMain.add(jPanel7, "card2");

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setActiveButton(jButton1);
        CardLayout bt1 = (CardLayout) pnMain.getLayout();
        bt1.show(pnMain,"pnScreenQuanLyBanAn");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setActiveButton(jButton2);
        CardLayout bt2 = (CardLayout) pnMain.getLayout();
        bt2.show(pnMain ,"pnScreenDatBanMoi");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setActiveButton(jButton3);
        CardLayout bt3 = (CardLayout) pnMain.getLayout();
        bt3.show(pnMain, "pnScreenDanhSach");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCountEmpty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountEmpty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountEmpty1ActionPerformed

    private void txtCountBooked1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountBooked1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountBooked1ActionPerformed

    private void txtCountUsing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountUsing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountUsing1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setActiveButton(jButton4);
        CardLayout bt4 = (CardLayout) pnMain.getLayout();
        bt4.show(pnMain, "pnScreenDanhSachEmployee");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        // 1. Kiểm tra nếu có tài khoản đang đăng nhập
        setActiveButton(btnLogOut);
        if (this.AccCurrent != null) {
            // 2. Gọi hàm updateActive để set isActive = FALSE
            acc.updateActive(false, this.AccCurrent.getUsername());
        }

        // 3. Hiển thị lại màn hình đăng nhập và đóng form Main_menu
        loginUI.show(); // Hoặc new JFLoginUI().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogOutActionPerformed

    // ... (Sau tất cả các hàm ActionPerformed) ...

private void setButtonDesign(javax.swing.JButton button, boolean isActive) {
    if (isActive) {
        // Màu Active: Màu xanh (điều chỉnh RGB theo ý muốn)
        button.setBackground(new java.awt.Color(0, 101, 234)); 
        button.setForeground(new java.awt.Color(255, 255, 255)); 
    } else {
        // Màu Inactive: Màu nền Menu (điều chỉnh RGB theo ý muốn)
        button.setBackground(new java.awt.Color(26, 41, 59)); 
        button.setForeground(new java.awt.Color(238, 238, 238));
    }
}

// ... (Sau hàm setButtonDesign) ...

public void setActiveButton(javax.swing.JButton currentButton) {
    // 1. Đặt lại màu cho nút đang Active trước đó (Inactive)
    if (activeButton != null) {
        setButtonDesign(activeButton, false); 
    }

    // 2. Thiết lập trạng thái Active cho nút mới
    setButtonDesign(currentButton, true); 

    // 3. Lưu trữ nút mới làm nút Active
    activeButton = currentButton;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Main_menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel main1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel screenQuanLyBan1;
    private javax.swing.JPanel sodobanan1;
    private javax.swing.JPanel tableListPanel1;
    private javax.swing.JPanel thongkebanan1;
    private javax.swing.JPanel titleQLB1;
    private javax.swing.JTextField txtCountBooked1;
    private javax.swing.JTextField txtCountEmpty1;
    private javax.swing.JTextField txtCountUsing1;
    // End of variables declaration//GEN-END:variables
}
