/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;

import quanlydatban.Model.Table;
import javax.swing.JPanel;
import quanlydatban.Service.TableService;
/**
 *
 * @author HELLO
 */
public class pnScreenQuanLyBanAn extends JPanel implements  TableUpdateListener  {
    List<Table> tbList =new ArrayList<Table> ();
    /**
     * Creates new form NewJPanel
     */
    


    private TableUpdateListener datBanMoiListener; 
    
    //Nhận sự thay đổi từ DatBanMoi
    public void setDatBanMoiListener(TableUpdateListener listener) {
        this.datBanMoiListener = listener;
    }

// 3. Chỉnh sửa onTableStatusUpdated()
@Override
    public void onTableStatusUpdated() {
    uploadTable(); 
    // Thêm bước chuyển tiếp sự kiện
    if (datBanMoiListener != null) {
        datBanMoiListener.onTableStatusUpdated(); 
        }
    }
    public pnScreenQuanLyBanAn() {
        initComponents();
        uploadTable();
    }
   
    
    public void uploadTablefromDataBase(){
        tbList.clear();
        TableService tbs = new TableService();
        this.tbList= tbs.getTbList();
        
    }
    public void uploadTable(){
        
        uploadTablefromDataBase();
        int count1=0, count2=0 , count3=0;
        this.tableListPanel.removeAll();
        
        this.tableListPanel.setLayout(new GridLayout(0, 4, 10, 10));
        for(int i = 0 ; i<tbList.size() ;i++){
            cardTable card = new cardTable();
            Table temp= tbList.get(i);
            card.setTxtIdTable(temp.getIdTable());
            card.setTxtTrangThai(temp.getStatusTable());
            card.setTxtSeats(temp.getSeats());
            
            card.setTableId(temp.getIdTable());
            card.setUpdateListener(this);
            
            String status = tbList.get(i).getStatusTable();
            if(status.equalsIgnoreCase("Trống")){
                count1++;
            }
            else if(status.equalsIgnoreCase("Đã Đặt")){
                count2++;
            }
            else{ 
                count3++;
            }
            this.tableListPanel.add(card);
        }
        this.txtCountEmpty.setText(""+count1);
        this.txtCountBooked.setText(""+count2);
        this.txtCountUsing.setText(""+count3);
        tableListPanel.revalidate();
        tableListPanel.repaint();
    }
    
    // Trong pnScreenQuanLyBanAn.java (thêm vào cuối class, trước dấu } cuối cùng)

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleQLB = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        thongkebanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCountEmpty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCountBooked = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCountUsing = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sodobanan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        titleQLB.setBackground(new java.awt.Color(247, 250, 252));
        titleQLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 232, 240)));
        titleQLB.setPreferredSize(new java.awt.Dimension(870, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Quản lý bàn ăn");

        javax.swing.GroupLayout titleQLBLayout = new javax.swing.GroupLayout(titleQLB);
        titleQLB.setLayout(titleQLBLayout);
        titleQLBLayout.setHorizontalGroup(
            titleQLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleQLBLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel3)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        titleQLBLayout.setVerticalGroup(
            titleQLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleQLBLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(titleQLB, java.awt.BorderLayout.PAGE_START);

        main.setLayout(new java.awt.BorderLayout());

        thongkebanan.setBackground(new java.awt.Color(255, 255, 255));
        thongkebanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 232, 240)));

        jPanel1.setBackground(new java.awt.Color(237, 233, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(128, 128, 128)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(255, 255, 255))));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bàn trống");

        txtCountEmpty.setBackground(new java.awt.Color(237, 233, 216));
        txtCountEmpty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountEmpty.setForeground(new java.awt.Color(0, 141, 46));
        txtCountEmpty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountEmpty.setBorder(null);
        txtCountEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountEmptyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(txtCountEmpty, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountEmpty)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(237, 233, 216));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(128, 128, 128)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(255, 255, 255))));
        jPanel2.setPreferredSize(new java.awt.Dimension(233, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Đã đặt");

        txtCountBooked.setBackground(new java.awt.Color(237, 233, 216));
        txtCountBooked.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountBooked.setForeground(new java.awt.Color(255, 133, 0));
        txtCountBooked.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountBooked.setBorder(null);
        txtCountBooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountBookedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtCountBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountBooked, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(237, 233, 216));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(128, 128, 128)), javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(255, 255, 255))));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Đang dùng");

        txtCountUsing.setBackground(new java.awt.Color(237, 233, 216));
        txtCountUsing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountUsing.setForeground(new java.awt.Color(242, 0, 39));
        txtCountUsing.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountUsing.setBorder(null);
        txtCountUsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountUsingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCountUsing, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountUsing)
                .addGap(14, 14, 14))
        );

        jLabel7.setText("Thống kê bàn ăn");

        javax.swing.GroupLayout thongkebananLayout = new javax.swing.GroupLayout(thongkebanan);
        thongkebanan.setLayout(thongkebananLayout);
        thongkebananLayout.setHorizontalGroup(
            thongkebananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkebananLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(thongkebananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongkebananLayout.setVerticalGroup(
            thongkebananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongkebananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thongkebananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        main.add(thongkebanan, java.awt.BorderLayout.PAGE_START);

        sodobanan.setLayout(new java.awt.BorderLayout());

        tableListPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableListPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(128, 128, 128)));
        jScrollPane1.setViewportView(tableListPanel);

        sodobanan.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        main.add(sodobanan, java.awt.BorderLayout.CENTER);

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCountEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountEmptyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountEmptyActionPerformed

    private void txtCountBookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountBookedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountBookedActionPerformed

    private void txtCountUsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountUsingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountUsingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel sodobanan;
    private javax.swing.JPanel tableListPanel;
    private javax.swing.JPanel thongkebanan;
    private javax.swing.JPanel titleQLB;
    private javax.swing.JTextField txtCountBooked;
    private javax.swing.JTextField txtCountEmpty;
    private javax.swing.JTextField txtCountUsing;
    // End of variables declaration//GEN-END:variables

}
