/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;
import quanlydatban.Dao.EmployeeDao; // Phải có để lấy dữ liệu
import quanlydatban.Model.Employee; // Phải có để dùng đối tượng Employee
import java.util.List;
import javax.swing.table.DefaultTableModel; // Phải có để quản lý dữ liệu bảng
import javax.swing.JOptionPane; // Để hiển thị thông báo lỗi
import quanlydatban.Dao.ConnectionDatabase;
import quanlydatban.View.dangnhap.RoundedBorder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author HELLO
 */
public class pnScreenDanhSachEmployee extends javax.swing.JPanel {
    // ... (bên trong public class pnScreenDanhSachEmployee extends javax.swing.JPanel { ) ...
    private RoundedBorder roundedBorder;
    public pnScreenDanhSachEmployee() {
        initComponents();
        loadDataToTable();
        applyRoundedBorder();
    
    }
    private void applyRoundedBorder() {
        int radius = 15; // Chọn bán kính bo tròn
        roundedBorder = new RoundedBorder(radius);

        // Áp dụng cho các nút
        if (jButton1 != null) jButton1.setBorder(roundedBorder);
        if (jButton2 != null) jButton2.setBorder(roundedBorder);
        
        // Tùy chọn: Áp dụng cho khung JScrollPane chứa JTable
        if (jScrollPane1 != null) {
            jScrollPane1.setBorder(roundedBorder);
        }
    }
    
   private void loadDataToTable() {
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"ID", "Họ và Tên", "Ngày sinh", "Giới Tính", "Số điện thoại", "Địa Chỉ", "Lương", "Chức Vụ"},
        0
    );

    EmployeeDao dao = new EmployeeDao();
    
    try {
        // 2a. THAY ĐỔI: GỌI phương thức getEmployee() để TẢI DỮ LIỆU vào biến list nội bộ của DAO
        dao.getEmployee(); 
        
        // 2b. THAY ĐỔI: Lấy danh sách đã được tải ra bằng getList()
        List<Employee> employeeList = dao.getList();
        
        // 3. Duyệt qua danh sách và thêm từng dòng vào Model
        for (Employee emp : employeeList) {
            model.addRow(new Object[]{
                emp.getIdEmploy(),
                emp.getName(),
                emp.getDoB(),
                emp.getGender(),
                emp.getPhone(),
                emp.getAddress(),
                emp.getSalary(),
                emp.getRole()
            });
        }
        
        // 4. Đặt Model vào JTable
        jTable1.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu nhân viên: " + e.getMessage(), 
                                      "Lỗi Database", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

    /**
     * Creates new form pnScreenDanhSachEmployee
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ và Tên", "Ngày sinh", "Giới Tính", "Số điện thoại", "Địa Chỉ", "Lương", "Chức Vụ"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(800, 500));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Thêm Nhân Viên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa Nhân Viên");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          pnScreenThemNhanVien addEmployeeFrame = new pnScreenThemNhanVien();
        addEmployeeFrame.setVisible(true);
        addEmployeeFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      // Đã xóa code gắn sự kiện đệ quy khỏi đây
      int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa trong bảng.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 1. Lấy ID từ cột đầu tiên (index 0)
    Object idValue = jTable1.getValueAt(selectedRow, 0); 
    int employeeId;
    
    try {
        employeeId = Integer.parseInt(idValue.toString());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Không thể lấy ID nhân viên. Dữ liệu bảng bị lỗi.", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 2. Hộp thoại xác nhận
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Bạn có chắc chắn muốn xóa nhân viên ID: " + employeeId + " không?", 
        "Xác nhận xóa", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        EmployeeDao dao = new EmployeeDao();
        try {
            // 3. Thực hiện xóa (Cần phương thức deleteEmployee(int id) trong EmployeeDao)
            boolean success = dao.deleteEmployee(employeeId); 
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                loadDataToTable(); // 4. Tải lại bảng sau khi xóa
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên hoặc thao tác xóa thất bại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi Database khi xóa: " + e.getMessage(), "Lỗi SQL", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
