/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlydatban.Model.Booking;
import quanlydatban.Model.Customer;
import quanlydatban.Model.Table;
import quanlydatban.Service.BookingService;
import quanlydatban.Service.CustomerService;


/**
 *
 * @author HELLO
 */
public class pnScreenDanhSach extends javax.swing.JPanel implements TableUpdateListener {
    
    private TableUpdateListener datbanmoiListener;
    BookingService bks = new BookingService();
    /**
     * Creates new form pnScreenDanhSach
     */
    public pnScreenDanhSach() {
        initComponents();
        setCount();
        ViewTable();
    }
    private void ViewTable(){
        
        
        
        DefaultTableModel model = (DefaultTableModel) this.tbMain.getModel();
        model.setNumRows(0);
        
        for(Booking x : bks.getAllBooking()){
            CustomerService cus = new CustomerService();
            Customer temp = cus.getCus(x.getIDcus());
            
            model.addRow(new Object[] {x.getIdBooking() ,x.getIDtable() , temp.getNameCus() , temp.getCusPhone(), x.getTimeStart(),x.getGuestCount() ,x.getNote() });
        }
        this.tbMain.revalidate();
        this.tbMain.repaint();
    }
    private void setCount(){
        int countTongBooking=0;
        for(Booking x: bks.getAllBooking() ){
            countTongBooking++;
        }
        
        this.txtTongBooking.setText(""+countTongBooking);
    }
    // Trong pnScreenDanhSach.java

private void deleteSelectedBooking(int selectedRowIndex , int idTable) {
    // 1. Lấy ID Booking từ JTable (chỉ để hiển thị thông báo xác nhận)
    DefaultTableModel model = (DefaultTableModel) tbMain.getModel();
    Object bookingIdObj = model.getValueAt(selectedRowIndex, 0); 
    String bookingIdStr = String.valueOf(bookingIdObj);
    
    // 2. Kiểm tra và xác nhận xóa
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Bạn có chắc muốn xóa đơn đặt bàn ID: " + bookingIdStr + " khỏi danh sách hiển thị?", 
        "Xác nhận xóa khỏi UI", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        
        try {
            // ************ BƯỚC QUAN TRỌNG NHẤT ************
            // XÓA HÀNG KHỎI JTable (MODEL)
            model.removeRow(selectedRowIndex); 
            bks.DeteteBooking(idTable);
            bks.ResetStatus(idTable);
            
            JOptionPane.showMessageDialog(this, 
                                          "Đơn đặt bàn ID " + bookingIdStr + " đã được xóa ", 
                                          "Thông báo", 
                                          JOptionPane.INFORMATION_MESSAGE);
            
            // 3. Cập nhật lại giao diện và thống kê
            
            // Cập nhật lại UI (Đã có trong ViewTable, nhưng nên gọi lại để làm sạch)
            this.tbMain.revalidate();
            this.tbMain.repaint();
            
            // Cần gọi lại logic tính toán thống kê (nếu thống kê phụ thuộc vào số hàng trong bảng)
            // Hoặc gọi ViewTable() nếu bạn muốn làm mới toàn bộ từ DB:
            // ViewTable(); // Tuy nhiên, nếu gọi ViewTable() thì hàng vừa xóa lại hiện ra, nên không gọi.
            
            // Cập nhật thống kê (Nếu txtCountEmpty là Tổng số đơn):
            // Tính lại tổng số hàng còn lại
            // int remainingCount = model.getRowCount();
            // this.txtCountEmpty.setText(String.valueOf(remainingCount));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa hàng khỏi UI.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenDanhSach = new javax.swing.JPanel();
        pnTitle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        thongkedatban = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTongBooking = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCountEmpty3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(870, 500));
        setLayout(new java.awt.BorderLayout());

        screenDanhSach.setLayout(new java.awt.BorderLayout());

        pnTitle.setBackground(new java.awt.Color(255, 204, 204));
        pnTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTitle.setPreferredSize(new java.awt.Dimension(870, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh Sách Đặt Bàn");

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTitleLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );

        screenDanhSach.add(pnTitle, java.awt.BorderLayout.PAGE_START);

        main.setLayout(new java.awt.BorderLayout());

        thongkedatban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tổng Số Bàn Đã Đặt");

        txtTongBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongBooking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTongBooking.setBorder(null);
        txtTongBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(txtTongBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongBooking)
                .addGap(12, 12, 12))
        );

        jLabel7.setText("Thống kê đặt bàn:");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(349, 74));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hoàn Thành");

        txtCountEmpty3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCountEmpty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCountEmpty3.setBorder(null);
        txtCountEmpty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountEmpty3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtCountEmpty3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCountEmpty3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout thongkedatbanLayout = new javax.swing.GroupLayout(thongkedatban);
        thongkedatban.setLayout(thongkedatbanLayout);
        thongkedatbanLayout.setHorizontalGroup(
            thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongkedatbanLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(thongkedatbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongkedatbanLayout.setVerticalGroup(
            thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongkedatbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thongkedatbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        main.add(thongkedatban, java.awt.BorderLayout.PAGE_START);

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Booking", "Ban ", "Khach hang", "Dien Thoai", "Thoi Gian Dung", "So Khach", "Ghi Chu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMain.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        tbMain.setPreferredSize(new java.awt.Dimension(700, 1000));
        tbMain.setRowHeight(40);
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbMainKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbMain);
        if (tbMain.getColumnModel().getColumnCount() > 0) {
            tbMain.getColumnModel().getColumn(0).setResizable(false);
            tbMain.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbMain.getColumnModel().getColumn(1).setResizable(false);
            tbMain.getColumnModel().getColumn(1).setPreferredWidth(40);
            tbMain.getColumnModel().getColumn(2).setResizable(false);
            tbMain.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbMain.getColumnModel().getColumn(3).setResizable(false);
            tbMain.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbMain.getColumnModel().getColumn(4).setResizable(false);
            tbMain.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbMain.getColumnModel().getColumn(5).setResizable(false);
            tbMain.getColumnModel().getColumn(5).setPreferredWidth(30);
            tbMain.getColumnModel().getColumn(6).setResizable(false);
            tbMain.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jLabel1.setText("Danh sach dat ban :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Hoàn Thành");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setText("Xóa Đơn ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(214, 214, 214))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(47, 47, 47))))
        );

        main.add(jPanel3, java.awt.BorderLayout.CENTER);

        screenDanhSach.add(main, java.awt.BorderLayout.CENTER);

        add(screenDanhSach, java.awt.BorderLayout.CENTER);
        screenDanhSach.getAccessibleContext().setAccessibleName("pnScreenDanhSach");
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongBookingActionPerformed

    private void txtCountEmpty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountEmpty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountEmpty3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n = this.tbMain.getSelectedRow();
        int id = (int) this.tbMain.getValueAt(n, 0);
        deleteSelectedBooking(n , id);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbMainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMainKeyPressed
//    public void setDatbanmoiListener(TableUpdateListener listener) {
//        this.datbanmoiListener = listener;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnTitle;
    private javax.swing.JPanel screenDanhSach;
    private javax.swing.JTable tbMain;
    private javax.swing.JPanel thongkedatban;
    private javax.swing.JTextField txtCountEmpty3;
    private javax.swing.JTextField txtTongBooking;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onTableStatusUpdated() {
        setCount();
        ViewTable();
        if (datbanmoiListener != null) {
            this.datbanmoiListener.onTableStatusUpdated(); 
        }
        this.tbMain.revalidate();
        this.tbMain.repaint();
    }
}
