/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlydatban.View.HomePage;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import quanlydatban.Model.Table;
import quanlydatban.Service.TableService;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import quanlydatban.Model.Account;
import quanlydatban.Model.Employee;
import quanlydatban.Service.BookingService;
import quanlydatban.Service.CustomerService;
import quanlydatban.Service.EmployeeService;



/**implements TableUpdateListener
 *
 * @author HELLO
 */
public class pnScreenDatBanMoi extends javax.swing.JPanel implements TableUpdateListener {
    
    private Main_menu parentFrame;
   
    private Employee Emp = null;
    private TableUpdateListener quanLyBanListener;

    public pnScreenDatBanMoi(Main_menu temp)  {
        
        parentFrame = temp;
        setCurrentEmp();
        initComponents();
        cbChonBan.setModel(new javax.swing.DefaultComboBoxModel());
        loadTabletoComboBox();
        ViewTable();
    }
    
    private void ViewTable(){
        TableService list = new TableService();
        DefaultTableModel model = (DefaultTableModel) this.tableEmpty.getModel();
        model.setNumRows(0);
        for(Table x: list.getTbList()){
            if(x.getStatusTable().equalsIgnoreCase("Empty")){
                String mode = "Sẵn sàng";
                model.addRow(new Object[] {x.getIdTable(),x.getSeats(),mode});
            }
        }
    }
    private void loadTabletoComboBox(){
        TableService list = new TableService();
        
        cbChonBan.removeAllItems();
        cbChonBan.addItem("--- Chọn ID Bàn ---");
        
        for(Table x : list.getTbList()){
            if(x.getStatusTable().equalsIgnoreCase("Empty")){
                ((javax.swing.JComboBox) cbChonBan).addItem(x.getIdTable());
            }
        }
        if(cbChonBan.getItemCount()==1){
            cbChonBan.removeAllItems();
            cbChonBan.addItem("Hêt Bàn Rồi :((");
        }
    }
    private void resetForm(){
        this.txtTenKH.setText("");
        this.txtSDT.setText("");
        this.txtTimeStarted.setText("");
        this.txtGhiChu.setText("");
        this.txtSoKhach.setText("");
        cbChonBan.setSelectedIndex(0);
    }
    private void setCurrentEmp() {
        EmployeeService emp = new EmployeeService();
        try {
            this.Emp = emp.getCurrentEmp(parentFrame.AccCurrent.getUsername());
        } catch (SQLException ex) {
            System.getLogger(pnScreenDatBanMoi.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    } 
    public void setQuanLyBanListener(TableUpdateListener listener) {
        this.quanLyBanListener = listener;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screenDatBanMoi = new javax.swing.JPanel();
        titleTDDBM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mainTaoDon = new javax.swing.JPanel();
        pnThongTinKH = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSoKhach = new javax.swing.JTextField();
        btnDeleteAll = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        txtTimeStarted = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cbChonBan = new javax.swing.JComboBox<>();
        pnBanTrong = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEmpty = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(863, 1100));

        screenDatBanMoi.setBackground(new java.awt.Color(255, 255, 204));
        screenDatBanMoi.setLayout(new java.awt.BorderLayout());

        titleTDDBM.setBackground(new java.awt.Color(204, 255, 204));
        titleTDDBM.setPreferredSize(new java.awt.Dimension(870, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Tạo đơn đặt bàn mới");

        javax.swing.GroupLayout titleTDDBMLayout = new javax.swing.GroupLayout(titleTDDBM);
        titleTDDBM.setLayout(titleTDDBMLayout);
        titleTDDBMLayout.setHorizontalGroup(
            titleTDDBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleTDDBMLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel8)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        titleTDDBMLayout.setVerticalGroup(
            titleTDDBMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleTDDBMLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        screenDatBanMoi.add(titleTDDBM, java.awt.BorderLayout.PAGE_START);

        mainTaoDon.setLayout(new java.awt.BorderLayout());

        pnThongTinKH.setBackground(new java.awt.Color(255, 204, 204));
        pnThongTinKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnThongTinKH.setPreferredSize(new java.awt.Dimension(870, 300));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("Thông tin khách hàng");

        jLabel10.setText("Tên khách hàng :");

        jLabel12.setText("Chọn bàn :");

        jLabel13.setText("Số điện thoại :");

        jLabel14.setText("Giờ hẹn :");

        jLabel15.setText("Số khách :");

        btnDeleteAll.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteAll.setText("Xóa Form");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(153, 255, 153));
        btnConfirm.setText("Tạo đơn");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        txtTimeStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeStartedActionPerformed(evt);
            }
        });

        jLabel16.setText("Ghi chú :");

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });

        cbChonBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChonBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinKHLayout = new javax.swing.GroupLayout(pnThongTinKH);
        pnThongTinKH.setLayout(pnThongTinKHLayout);
        pnThongTinKHLayout.setHorizontalGroup(
            pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinKHLayout.createSequentialGroup()
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinKHLayout.createSequentialGroup()
                        .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimeStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtSoKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cbChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(pnThongTinKHLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteAll)))
                .addGap(29, 29, 29)
                .addComponent(btnConfirm)
                .addGap(49, 49, 49))
            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinKHLayout.setVerticalGroup(
            pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeStarted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAll)
                    .addComponent(btnConfirm))
                .addGap(19, 19, 19))
        );

        mainTaoDon.add(pnThongTinKH, java.awt.BorderLayout.PAGE_START);

        pnBanTrong.setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 1, 1, 1));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 500));

        tableEmpty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Số chỗ ngồi", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmpty.setPreferredSize(new java.awt.Dimension(170, 200));
        tableEmpty.setRowHeight(25);
        tableEmpty.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableEmpty);
        if (tableEmpty.getColumnModel().getColumnCount() > 0) {
            tableEmpty.getColumnModel().getColumn(0).setResizable(false);
            tableEmpty.getColumnModel().getColumn(1).setResizable(false);
            tableEmpty.getColumnModel().getColumn(2).setResizable(false);
        }

        pnBanTrong.add(jScrollPane2);

        mainTaoDon.add(pnBanTrong, java.awt.BorderLayout.CENTER);

        screenDatBanMoi.add(mainTaoDon, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(screenDatBanMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(screenDatBanMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        resetForm();
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void txtTimeStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeStartedActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTimeStartedActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void cbChonBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChonBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChonBanActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        BookingService bks = new BookingService();
        CustomerService cus = new CustomerService();
        cus.addCus(this.txtTenKH.getText(),this.txtSDT.getText() );
        
        
        int idEmp = this.Emp.getIdEmploy();
        String time = this.txtTimeStarted.getText();
        int seat = Integer.parseInt(this.txtSoKhach.getText());
        String note = this.txtGhiChu.getText();
        int IDcus =cus.getIdCus(this.txtSDT.getText());
        int idTable =Integer.parseInt((String)cbChonBan.getSelectedItem());
        
        try {
            if(bks.insertBooking(time, seat, note,idEmp ,IDcus ,idTable)){
                JOptionPane.showMessageDialog(null, "Thêm đơn đặt thành công , " + idTable, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            if (quanLyBanListener != null) {
                    quanLyBanListener.onTableStatusUpdated();
                }
        } catch (SQLException ex) {
            System.getLogger(pnScreenDatBanMoi.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(null, "Thêm đơn đặt thất bại ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        
        onTableStatusUpdated();
;
        
        
        
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JComboBox<String> cbChonBan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainTaoDon;
    private javax.swing.JPanel pnBanTrong;
    private javax.swing.JPanel pnThongTinKH;
    private javax.swing.JPanel screenDatBanMoi;
    private javax.swing.JTable tableEmpty;
    private javax.swing.JPanel titleTDDBM;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoKhach;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JFormattedTextField txtTimeStarted;
    // End of variables declaration//GEN-END:variables

    // Trong pnScreenDatBanMoi.java
    @Override
    public void onTableStatusUpdated() {
        resetForm();
        ViewTable();
        loadTabletoComboBox();
        // THÊM CÁC LỆNH NÀY để đảm bảo JTable được làm mới trên giao diện
        this.tableEmpty.revalidate();
        this.tableEmpty.repaint();
        // Hoặc làm mới toàn bộ JPanel chứa JTable
        this.pnBanTrong.revalidate();
        this.pnBanTrong.repaint();
    }

    
}
